volumes:
  data:

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    volumes:
      - data:/data/db
  redis:
    image: redis:latest
    volumes:
      - data:/data
  post-it-backend:
    image: post-it-backend:latest
    environment:
      - JWT_SECRET=myKeyFromEnv
      - MONGO_CONNECTION=mongodb://docker:mongopw@mongodb:27017
      - REDIS_CONNECTION=redis://default:redispw@redis:6379
    ports:
      - 80:8080
