volumes:
  data:

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    volumes:
      - data:/data/db
  redis:
    container_name: redis
    image: redis:latest
    volumes:
      - data:/data
  post-it-backend:
    container_name: backend
    image: post-it-backend:latest
    environment:
      - JWT_SECRET=myKeyFromEnv
      - MONGO_CONNECTION=mongodb://docker:mongopw@mongodb:27017
      - REDIS_CONNECTION=redis://default:redispw@redis:6379
      - WARN=off
    ports:
      - 8080:8080
  post-it-frontend:
    container_name: frontend
    image: post-it-frontend:latest
    ports:
      - 80:80
    